name: build for staging

on:
  push:
    branches:
      - 'staging'

jobs:
  build-mod:
    name: Build Mod
    runs-on: ubuntu-latest
    env:
      MODKIT_VERSION: 0.12.0.00-beta-release-905
      ECO_BRANCH: staging
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Fetch dependencies
      run: dotnet restore ./EcoCompaniesMod/EcoCompaniesMod.csproj
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Build
      run: dotnet build ./EcoCompaniesMod/EcoCompaniesMod.csproj --configuration Release --no-restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-binaries-staging
        path: EcoCompaniesMod/bin/Release/net8.0/EcoCompaniesMod.*
